<Project>
  <PropertyGroup>
    <SolutionRoot>$(MSBuildThisFileDirectory)</SolutionRoot>
  </PropertyGroup>

  <!-- Import our shared user configuration file -->
  <Import
    Project="$(SolutionRoot)Config.Build.user.props"
    Condition="Exists('$(SolutionRoot)Config.Build.user.props')"
  />

  <!-- Shared Thunderstore metadata -->
  <PropertyGroup>
    <ThunderstoreTeam>Test_Team</ThunderstoreTeam>
    <!-- TODO: Add a link to your mod repository here (optional) -->
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>

  <!-- Shared NuGet metadata -->
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <!--
      TODO: Fill these values. See:
      https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
    -->
    <Authors></Authors>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>How to Fish;$(PackageTags)</PackageTags>
  </PropertyGroup>

  <!-- Shared primary configuration for the project -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>recommended</AnalysisMode>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
  </PropertyGroup>

  <!-- Shared custom props -->
  <PropertyGroup>
    <PathBeforeSteam Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.local/share/</PathBeforeSteam>
    <PathBeforeSteam Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(MSBuildProgramFiles32)/</PathBeforeSteam>
    <HowToFishGameRootDir Condition="$(HowToFishGameRootDir) == ''">$(PathBeforeSteam)Steam/steamapps/common/How to Fish/</HowToFishGameRootDir>
    <HowToFishBepInExDir Condition="$(HowToFishBepInExDir) == ''">$(HowToFishGameRootDir)/BepInEx/</HowToFishBepInExDir>
    <ManagedDir>$(HowToFishGameRootDir)/How to Fish_Data/Managed/</ManagedDir>
  </PropertyGroup>
</Project>
