<Project Sdk="Microsoft.NET.Sdk">
  <!-- Project properties -->
  <PropertyGroup>
<!--#if (!no-tutorial) -->
    <!-- This is the most appropriate target framework for the game's Unity version. -->
<!--#endif -->
    <TargetFramework>netstandard2.1</TargetFramework>
<!--#if (!no-tutorial) -->
    <!-- This is the global identifier for your mod. This should not be changed after release. -->
<!--#endif -->
    <AssemblyName>_Guid_</AssemblyName>
<!--#if (!no-tutorial) -->
    <!-- This is the display name of your mod. -->
<!--#endif -->
    <AssemblyTitle>BepInExModTemplate</AssemblyTitle>
<!--#if (!no-tutorial) -->
    <!-- The version number for your assembly, BepInEx plugin, and Thunderstore package. -->
<!--#endif -->
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- ThunderPipe properties -->
  <PropertyGroup>
<!--#if (!no-tutorial) -->
    <!-- Whether or not this project should build a Thunderstore package. -->
<!--#endif -->
    <IsThunderstorePackable>true</IsThunderstorePackable>
<!--#if (!no-tutorial) -->
    <!-- Package name on Thunderstore. Must not contain spaces ' ' or dashes '-'. -->
<!--#endif -->
    <ThunderstoreName>BepInExModTemplate</ThunderstoreName>
    <ThunderstoreDescription>TODO: Fill in short mod description at max 250 characters.</ThunderstoreDescription>
    <!--
      Communities and package categories metadata for publishing with ThunderPipe.
      Communities: https://thunderstore.io/api/experimental/community/
      Categories: https://thunderstore.io/api/experimental/community/how-to-fish/category/
    -->
    <ThunderstoreCommunities>how-to-fish</ThunderstoreCommunities>
    <ThunderstoreCategories>mods</ThunderstoreCategories>
  </PropertyGroup>

<!--#if (library) -->
  <!-- NuGet metadata -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--
      TODO: Fill these values. See:
      https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
    -->
    <PackageId></PackageId>
    <Description></Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(SolutionRoot)README.md" Pack="true" PackagePath="/" />
    <None Include="$(SolutionRoot)icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

<!--#endif -->
  <!--
    Define mod files to copy to the relative BepInEx directory after build
    and where they are packed to when building a Thunderstore package
  -->
  <ItemGroup>
<!--#if (!no-tutorial) -->
    <!-- TargetPath is the dll file produced during build. -->
<!--#endif -->
    <ModFile Include="$(TargetPath)" Destination="plugins/" />
<!--#if (!no-tutorial) -->
    <!--
      If your project needs additional files, e.g. asset bundles,
      you can add them here. Example:

      <ModFile Include="./Assets/bundle" Destination="plugins/" />
    -->
<!--#endif -->
  </ItemGroup>

  <!-- Thunderstore package metadata -->
  <ItemGroup>
    <ThunderstorePackageFile Include="$(SolutionRoot)README.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)CHANGELOG.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)icon.png" />
    <ThunderstorePackageFile Include="$(SolutionRoot)LICENSE" />

<!--#if (!no-tutorial) -->
    <!--
      A list of Thunderstore packages this package requires at runtime.
      Note: This does NOT mark these as dependencies for this C# project;
            that must be done separately with PackageReference items.
    -->
<!--#endif -->
    <ThunderstoreDependency Include="BepInEx-BepInExPack" Version="5.4.2305" />
  </ItemGroup>
<!--#if (!no-tutorial) -->

  <!--
    To reference mod assemblies from Thunderstore packages via NuGet,
    this project includes the following NuGet feed:
    https://nuget.windows10ce.com/nuget/v3/index.json

    With this, you can simply depend on a Thunderstore package like so:

    <ItemGroup>
      <PackageReference Include="ModTeam-ModName" Version="*" />
    </ItemGroup>

    This will cause the mod to be downloaded and its
    methods will be available at compile time for your code.

    Note that this does NOT mark the package as a dependency
    for your Thunderstore package.
  -->
<!--#endif -->
</Project>
