<Project Sdk="Microsoft.NET.Sdk">
  <!-- Project properties -->
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>AuthorName.ModName</AssemblyName>
    <AssemblyTitle>ManyOptionsTest</AssemblyTitle>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- ThunderPipe properties -->
  <PropertyGroup>
    <IsThunderstorePackable>true</IsThunderstorePackable>
    <ThunderstoreName>ManyOptionsTest</ThunderstoreName>
    <ThunderstoreDescription>TODO: Fill in short mod description at max 250 characters.</ThunderstoreDescription>
    <!--
      Communities and package categories metadata for publishing with ThunderPipe.
      Communities: https://thunderstore.io/api/experimental/community/
      Categories: https://thunderstore.io/api/experimental/community/how-to-fish/category/
    -->
    <ThunderstoreCommunities>how-to-fish</ThunderstoreCommunities>
    <ThunderstoreCategories>mods</ThunderstoreCategories>
  </PropertyGroup>

  <!-- NuGet metadata -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--
      TODO: Fill these values. See:
      https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
    -->
    <PackageId></PackageId>
    <Description></Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(SolutionRoot)README.md" Pack="true" PackagePath="/" />
    <None Include="$(SolutionRoot)icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

  <!--
    Define mod files to copy to the relative BepInEx directory after build
    and where they are packed to when building a Thunderstore package
  -->
  <ItemGroup>
    <ModFile Include="$(TargetPath)" Destination="plugins/" />
  </ItemGroup>

  <!-- Thunderstore package metadata -->
  <ItemGroup>
    <ThunderstorePackageFile Include="$(SolutionRoot)README.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)CHANGELOG.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)icon.png" />
    <ThunderstorePackageFile Include="$(SolutionRoot)LICENSE" />

    <ThunderstoreDependency Include="BepInEx-BepInExPack" Version="5.4.2305" />
  </ItemGroup>
</Project>
